name: 'Setup Python Environment'
description: 'Set up Python with development headers for building bindings using conda'

inputs:
  platform:
    description: 'Target platform (linux, windows, macos, macos-arm)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Python and binding dependencies
      shell: bash -el {0}  # Ensures conda environment is activated
      run: |
        echo "Installing Python and binding dependencies in conda environment..."
        
        # Install Python and essential binding tools via conda
        mamba install -y \
          python=3.11 \
          pybind11 \
          numpy \
          pip
        
        echo "Python installation complete!"

    - name: Install additional Python dependencies via pip
      shell: bash -el {0}
      run: |
        echo "Installing additional Python dependencies..."
        
        # Install any additional Python packages that might not be available in conda
        python -m pip install --upgrade pip
        
        # Add any pip-only dependencies here if needed
        # python -m pip install some-package
        
        echo "Python dependencies installation complete!"

    - name: Verify Python setup
      shell: bash -el {0}
      run: |
        echo "Verifying Python setup..."
        python --version
        python -c "import sys; print(f'Python executable: {sys.executable}')"
        python -c "import pybind11; print(f'pybind11 version: {pybind11.__version__}')"
        python -c "import pybind11; print(f'pybind11 includes: {pybind11.get_include()}')"
        python -c "import numpy; print(f'numpy version: {numpy.__version__}')"
        
        # Show conda environment info for debugging
        echo "Conda environment info:"
        which python
        which pip
        echo "Python setup verification complete!"